services:
  cms:
    build: .
    container_name: sanjanacms
    ports:
      - "2512:8080"
    volumes:
      - cms_data:/data
      - ./static/uploads:/app/static/uploads
    environment:
      - DB_Path=/data/cms.db
    restart: always

volumes:
  cms_data:
